apiVersion: v1
kind: Service
metadata:
  labels:
    run: javaapp
  name: javaapp
  namespace: default
spec:
  ports:
  - nodePort: 32631
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: javaapp
  type: NodePort
